"""Shared test fixtures for model-collapse-baselines."""

from __future__ import annotations

import pytest


@pytest.fixture()
def small_real_dataset():
    """A minimal HuggingFace Dataset standing in for real data."""
    from datasets import Dataset

    texts = [f"Real document number {i} with some content." for i in range(100)]
    return Dataset.from_dict({"text": texts})


@pytest.fixture()
def small_synthetic_dataset():
    """A minimal HuggingFace Dataset standing in for synthetic data."""
    from datasets import Dataset

    texts = [
        f"Synthetic document number {i} generated by a model." for i in range(80)
    ]
    return Dataset.from_dict({"text": texts})


@pytest.fixture()
def default_config() -> dict:
    """Minimal experiment config matching the default.yaml structure."""
    return {
        "experiment": {
            "name": "test_run",
            "seed": 42,
            "num_generations": 3,
            "output_dir": "data",
        },
        "base_model": "sshleifer/tiny-gpt2",
        "real_data": {
            "dataset": "openwebtext",
            "split": "train",
            "max_documents": 500,
            "max_length": 64,
        },
        "synthetic_generation": {
            "num_samples": 200,
            "max_new_tokens": 64,
            "temperature": 1.0,
            "top_p": 0.95,
            "batch_size": 8,
        },
        "training": {
            "epochs": 1,
            "batch_size": 4,
            "gradient_accumulation_steps": 1,
            "learning_rate": 2e-5,
            "warmup_ratio": 0.05,
            "weight_decay": 0.01,
            "max_steps": 50,
            "use_lora": False,
            "from_pretrained_each_generation": True,
        },
        "schedule": {
            "type": "zero",
        },
        "measurement": {
            "eval_samples": 100,
        },
    }
