"""Candidate rule generation using mock LLM with diverse prompt variants."""

from __future__ import annotations

import re
import textwrap
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Tuple


@dataclass
class IOExample:
    """An input-output example for rule synthesis."""

    input: Any
    output: Any
    domain: str = "general"
    description: str = ""


@dataclass
class CandidateRule:
    """A candidate rule generated by the synthesis process."""

    rule_id: str
    source_code: str
    description: str
    domain: str = "general"
    prompt_variant: str = "default"
    generation: int = 0

    def get_function(self) -> Optional[Callable]:
        """Compile and return the rule's function."""
        try:
            namespace: dict = {}
            exec(self.source_code, namespace)
            for name, obj in namespace.items():
                if callable(obj) and not name.startswith("_"):
                    return obj
        except Exception:
            pass
        return None


# --- Mock LLM templates for different prompt variants ---

_TEMPLATES: Dict[str, str] = {
    "direct": textwrap.dedent("""\
        def rule(x):
            {body}
    """),
    "mathematical": textwrap.dedent("""\
        def rule(x):
            # Mathematical formulation
            {body}
    """),
    "recursive": textwrap.dedent("""\
        def rule(x):
            # Recursive approach
            if isinstance(x, (list, tuple)) and len(x) <= 1:
                return x[0] if x else 0
            {body}
    """),
    "conditional": textwrap.dedent("""\
        def rule(x):
            # Conditional logic
            {body}
    """),
    "lambda_style": "{body}",
}


class CandidateGenerator:
    """Generates candidate rules from I/O examples using a mock LLM.

    The mock LLM uses pattern matching and templates to generate diverse
    candidate rules. In production, this would call an actual LLM API.
    """

    def __init__(
        self,
        llm_callable: Optional[Callable] = None,
        domain: str = "general",
    ) -> None:
        """Initialize the generator.

        Args:
            llm_callable: Optional callable for LLM generation.
                          If None, uses mock LLM.
            domain: Problem domain (e.g., "math", "string", "general").
        """
        self.llm_callable = llm_callable or self._mock_llm
        self.domain = domain
        self._rule_counter = 0

    def generate(
        self,
        examples: List[IOExample],
        domain: Optional[str] = None,
        n: int = 5,
    ) -> List[CandidateRule]:
        """Generate n candidate rules from I/O examples.

        Args:
            examples: List of input-output examples.
            domain: Optional domain override.
            n: Number of candidates to generate.

        Returns:
            List of CandidateRule objects.
        """
        domain = domain or self.domain
        candidates = []

        variant_names = list(_TEMPLATES.keys())

        for i in range(n):
            variant = variant_names[i % len(variant_names)]
            prompt = self._build_prompt(examples, domain, variant)
            response = self.llm_callable(prompt, examples, variant)
            rule = self._parse_rule(response, domain, variant)
            if rule is not None:
                candidates.append(rule)

        return candidates

    def generate_refinement(
        self,
        base_rule: CandidateRule,
        failures: List[Tuple[Any, Any, Any]],
        examples: List[IOExample],
    ) -> List[CandidateRule]:
        """Generate refined versions of a rule based on failure cases.

        Args:
            base_rule: The rule to refine.
            failures: List of (input, expected, actual) tuples.
            examples: Original examples.

        Returns:
            List of refined CandidateRule objects.
        """
        # Use mock LLM to generate refinements
        refined_candidates = []

        # Strategy 1: Add special cases for failures
        special_case_code = self._add_special_cases(base_rule, failures)
        if special_case_code:
            self._rule_counter += 1
            refined_candidates.append(
                CandidateRule(
                    rule_id=f"rule_{self._rule_counter:04d}",
                    source_code=special_case_code,
                    description=f"Refined {base_rule.rule_id} with special cases",
                    domain=base_rule.domain,
                    prompt_variant="refinement_special_case",
                    generation=base_rule.generation + 1,
                )
            )

        # Strategy 2: Try a completely different approach
        alt_candidates = self.generate(examples, base_rule.domain, n=2)
        for c in alt_candidates:
            c.generation = base_rule.generation + 1
        refined_candidates.extend(alt_candidates)

        return refined_candidates

    def _build_prompt(
        self, examples: List[IOExample], domain: str, variant: str
    ) -> str:
        """Build a prompt from examples."""
        lines = [f"Domain: {domain}", f"Variant: {variant}", "Examples:"]
        for ex in examples:
            lines.append(f"  {ex.input} -> {ex.output}")
        lines.append("Generate a Python function 'rule(x)' that maps inputs to outputs.")
        return "\n".join(lines)

    def _mock_llm(
        self,
        prompt: str,
        examples: List[IOExample],
        variant: str,
    ) -> str:
        """Mock LLM that generates rules based on pattern analysis.

        Analyzes the I/O examples to detect common patterns:
        - Linear: y = ax + b
        - Polynomial: y = ax^2 + bx + c
        - Identity: y = x
        - Constant: y = c
        - List operations: sum, length, etc.
        """
        if not examples:
            return "def rule(x):\n    return x"

        # Try to detect patterns
        pattern = self._detect_pattern(examples)
        return self._generate_from_pattern(pattern, examples, variant)

    def _detect_pattern(
        self, examples: List[IOExample]
    ) -> Dict[str, Any]:
        """Detect the pattern in I/O examples."""
        inputs = [ex.input for ex in examples]
        outputs = [ex.output for ex in examples]

        # Check if inputs and outputs are all numbers
        all_numeric = all(
            isinstance(i, (int, float)) and isinstance(o, (int, float))
            for i, o in zip(inputs, outputs)
        )

        if all_numeric:
            # Try linear fit: y = ax + b
            if len(inputs) >= 2:
                try:
                    x0, y0 = float(inputs[0]), float(outputs[0])
                    x1, y1 = float(inputs[1]), float(outputs[1])
                    if x1 != x0:
                        a = (y1 - y0) / (x1 - x0)
                        b = y0 - a * x0
                        # Verify with remaining examples
                        all_match = all(
                            abs(float(o) - (a * float(i) + b)) < 1e-9
                            for i, o in zip(inputs, outputs)
                        )
                        if all_match:
                            return {"type": "linear", "a": a, "b": b}
                except (ValueError, TypeError, ZeroDivisionError):
                    pass

            # Try quadratic: y = ax^2 + bx + c
            if len(inputs) >= 3:
                try:
                    xs = [float(i) for i in inputs[:3]]
                    ys = [float(o) for o in outputs[:3]]
                    # Solve system
                    x0, x1, x2 = xs
                    y0, y1, y2 = ys
                    denom = (x0 - x1) * (x0 - x2) * (x1 - x2)
                    if abs(denom) > 1e-12:
                        a = (x2 * (y1 - y0) + x1 * (y0 - y2) + x0 * (y2 - y1)) / denom
                        b = (x2**2 * (y0 - y1) + x1**2 * (y2 - y0) + x0**2 * (y1 - y2)) / denom
                        c = (x1 * x2 * (x1 - x2) * y0 + x2 * x0 * (x2 - x0) * y1 + x0 * x1 * (x0 - x1) * y2) / denom
                        all_match = all(
                            abs(float(o) - (a * float(i)**2 + b * float(i) + c)) < 1e-6
                            for i, o in zip(inputs, outputs)
                        )
                        if all_match and abs(a) > 1e-12:
                            return {"type": "quadratic", "a": a, "b": b, "c": c}
                except (ValueError, TypeError, ZeroDivisionError):
                    pass

            # Check constant
            if len(set(outputs)) == 1:
                return {"type": "constant", "value": outputs[0]}

            # Check identity
            if all(i == o for i, o in zip(inputs, outputs)):
                return {"type": "identity"}

            # Check multiply
            if all(isinstance(i, (int, float)) and i != 0 for i in inputs):
                ratios = [float(o) / float(i) for i, o in zip(inputs, outputs)]
                if all(abs(r - ratios[0]) < 1e-9 for r in ratios):
                    return {"type": "linear", "a": ratios[0], "b": 0.0}

        # Check list operations
        if all(isinstance(i, (list, tuple)) for i in inputs):
            if all(isinstance(o, (int, float)) for o in outputs):
                # Check sum
                if all(sum(i) == o for i, o in zip(inputs, outputs)):
                    return {"type": "list_sum"}
                # Check length
                if all(len(i) == o for i, o in zip(inputs, outputs)):
                    return {"type": "list_length"}
                # Check max
                if all(i and max(i) == o for i, o in zip(inputs, outputs)):
                    return {"type": "list_max"}
                # Check min
                if all(i and min(i) == o for i, o in zip(inputs, outputs)):
                    return {"type": "list_min"}

        # Check string operations
        if all(isinstance(i, str) for i in inputs):
            if all(isinstance(o, str) for o in outputs):
                if all(o == i.upper() for i, o in zip(inputs, outputs)):
                    return {"type": "string_upper"}
                if all(o == i[::-1] for i, o in zip(inputs, outputs)):
                    return {"type": "string_reverse"}
            if all(isinstance(o, int) for o in outputs):
                if all(o == len(i) for i, o in zip(inputs, outputs)):
                    return {"type": "string_length"}

        # Fallback: lookup table
        return {"type": "lookup", "mapping": dict(zip(map(str, inputs), outputs))}

    def _generate_from_pattern(
        self,
        pattern: Dict[str, Any],
        examples: List[IOExample],
        variant: str,
    ) -> str:
        """Generate code from detected pattern."""
        ptype = pattern["type"]

        if ptype == "linear":
            a, b = pattern["a"], pattern["b"]
            if b == 0:
                if a == int(a):
                    body = f"return int(x * {int(a)})"
                else:
                    body = f"return x * {a}"
            elif a == int(a) and b == int(b):
                body = f"return int(x * {int(a)} + {int(b)})"
            else:
                body = f"return x * {a} + {b}"

        elif ptype == "quadratic":
            a, b, c = pattern["a"], pattern["b"], pattern["c"]
            parts = []
            if abs(a) > 1e-12:
                if a == int(a):
                    parts.append(f"{int(a)} * x**2")
                else:
                    parts.append(f"{a} * x**2")
            if abs(b) > 1e-12:
                if b == int(b):
                    parts.append(f"{int(b)} * x")
                else:
                    parts.append(f"{b} * x")
            if abs(c) > 1e-12:
                if c == int(c):
                    parts.append(f"{int(c)}")
                else:
                    parts.append(f"{c}")
            expr = " + ".join(parts) if parts else "0"
            # Clean up double signs
            expr = expr.replace("+ -", "- ")
            body = f"return int(round({expr}))"

        elif ptype == "constant":
            body = f"return {pattern['value']!r}"

        elif ptype == "identity":
            body = "return x"

        elif ptype == "list_sum":
            body = "return sum(x)"

        elif ptype == "list_length":
            body = "return len(x)"

        elif ptype == "list_max":
            body = "return max(x)"

        elif ptype == "list_min":
            body = "return min(x)"

        elif ptype == "string_upper":
            body = "return x.upper()"

        elif ptype == "string_reverse":
            body = "return x[::-1]"

        elif ptype == "string_length":
            body = "return len(x)"

        elif ptype == "lookup":
            mapping = pattern["mapping"]
            body = f"mapping = {mapping!r}\n    return mapping.get(str(x), None)"

        else:
            body = "return x"

        code = f"def rule(x):\n    {body}\n"
        return code

    def _parse_rule(
        self, response: str, domain: str, variant: str
    ) -> Optional[CandidateRule]:
        """Parse a generated response into a CandidateRule.

        Args:
            response: Generated code string.
            domain: Problem domain.
            variant: Prompt variant used.

        Returns:
            CandidateRule if parsing succeeds, None otherwise.
        """
        code = response.strip()

        # Try to extract function definition if embedded in other text
        if "def rule" not in code and "def " in code:
            # Use as-is
            pass
        elif "def rule" not in code and "def " not in code:
            # Wrap in function
            code = f"def rule(x):\n    {code}\n"

        # Validate it compiles
        try:
            compile(code, "<generated>", "exec")
        except SyntaxError:
            return None

        self._rule_counter += 1
        return CandidateRule(
            rule_id=f"rule_{self._rule_counter:04d}",
            source_code=code,
            description=f"Generated rule ({variant})",
            domain=domain,
            prompt_variant=variant,
        )

    def _add_special_cases(
        self, base_rule: CandidateRule, failures: List[Tuple[Any, Any, Any]]
    ) -> Optional[str]:
        """Add special case handling for failure cases."""
        if not failures:
            return None

        # Build special case conditions
        conditions = []
        for inp, expected, actual in failures:
            conditions.append(f"    if x == {inp!r}:\n        return {expected!r}")

        conditions_code = "\n".join(conditions)

        # Extract the body of the original function
        original = base_rule.source_code.strip()

        # Insert special cases at the beginning of the function
        lines = original.split("\n")
        if lines and lines[0].startswith("def "):
            new_code = lines[0] + "\n" + conditions_code + "\n" + "\n".join(lines[1:])
            return new_code

        return None
